import assert from "node:assert/strict";
import test from "node:test";

import {
	MAX_PLAN_BYTES,
	parsePlanDocument,
	renderPlanDocument,
	replaceManagedProgressReport,
	splitManagedProgressReport,
	validateFastPlanRevision,
	validatePlanDocument,
} from "../plan-document.js";
import {
	BACKGROUND_CHANGES_PLAN,
	INVALID_PART_PARALLEL_PLAN,
	PART_MINIMAL_PLAN,
	PART_PARALLEL_PLAN,
	PART_PLAN,
	PART_PLAN_WITH_QUESTIONS,
	PART_SPLIT_PARALLEL_PLAN,
	STAGE_GROUPED_PLAN,
	WHY_WHAT_PLAN,
} from "./fixtures.mjs";

function errorCodes(markdown) {
	return validatePlanDocument(markdown).map((item) => item.code);
}

test("parses and round-trips canonical plans without a numeric identity", () => {
	for (const markdown of [PART_MINIMAL_PLAN, PART_PLAN, PART_PLAN_WITH_QUESTIONS, PART_PARALLEL_PLAN]) {
		const parsed = parsePlanDocument(markdown);
		assert.equal(parsed.ok, true, JSON.stringify(parsed.errors));
		assert.equal("version" in parsed.document, false);
		assert.equal(renderPlanDocument(parsed.document), markdown);
	}
	const parsed = parsePlanDocument(PART_PLAN);
	assert.deepEqual(parsed.document.parts.map((part) => part.id), ["A", "B", "C"]);
	assert.deepEqual(parsed.document.stages.map((stage) => stage.stepIds), [["A"], ["B"], ["C"]]);
});

test("retains answered questions and canonical optional sections", () => {
	const parsed = parsePlanDocument(PART_PLAN_WITH_QUESTIONS);
	assert.equal(parsed.ok, true, JSON.stringify(parsed.errors));
	assert.deepEqual(parsed.document.questionsAndAnswers, [
		{ question: "Should failed writes invalidate a valid cache entry?", answer: "No. Retain the last valid value." },
		{ question: "Must the public cache interface change?", answer: "No. Preserve compatibility." },
	]);
	assert.ok(errorCodes(PART_PLAN_WITH_QUESTIONS.replace("| Question | Answer |", "| Prompt | Reply |")).includes("invalid_questions_and_answers"));
	assert.ok(errorCodes(PART_PLAN_WITH_QUESTIONS.replace("## Approach", "## Questions & Answers\n\n| Question | Answer |\n|---|---|\n| Duplicate? | Yes. |\n\n## Approach")).includes("duplicate_section"));
});

test("validates parallel schedules and source-equivalent fast revisions", () => {
	const parsed = parsePlanDocument(PART_SPLIT_PARALLEL_PLAN);
	assert.equal(parsed.ok, true, JSON.stringify(parsed.errors));
	assert.deepEqual(parsed.document.parallelExecution.map((assignment) => assignment.partId), ["A", "B", "C", "D"]);
	assert.equal(validateFastPlanRevision(PART_PLAN, PART_SPLIT_PARALLEL_PLAN).ok, true);
	assert.ok(errorCodes(INVALID_PART_PARALLEL_PLAN).includes("duplicate_parallel_worker"));
	assert.equal(validateFastPlanRevision(PART_PLAN, PART_PARALLEL_PLAN.replace("Invalidate matching entries", "Delete matching entries")).ok, false);
});

test("uses one strict trailing Part Progress report", () => {
	const managed = replaceManagedProgressReport(PART_PLAN, ["☐ Define cache consistency", "☐ Implement reliable invalidation", "☐ Cover boundary behavior"]);
	assert.equal(managed.includes("<!-- Generated by Pi plan mode. Do not edit. -->"), false);
	assert.equal(splitManagedProgressReport(managed).report.heading, "## Part Progress");
	assert.equal(parsePlanDocument(managed).ok, true);
	assert.ok(errorCodes(managed.replace("## Part Progress", "## Step Progress")).includes("malformed_progress_report"));
	assert.throws(() => replaceManagedProgressReport(PART_PLAN, ["☐ A"], { heading: "## Step Progress" }), /Managed progress heading/);
});

test("rejects historical headings and status-bearing task shapes", () => {
	for (const markdown of [BACKGROUND_CHANGES_PLAN, WHY_WHAT_PLAN, STAGE_GROUPED_PLAN]) {
		assert.equal(parsePlanDocument(markdown).ok, false, markdown);
	}
	assert.ok(errorCodes(PART_PLAN.replace("### Part B —", "### Step 2 [pending] ")).includes("malformed_part_heading"));
	assert.ok(errorCodes(PART_PLAN.replace("## Context", "## Unsupported")).includes("unsupported_heading"));
});

test("keeps Part identities ordered beyond Z and rejects metadata drift", () => {
	const headings = Array.from({ length: 27 }, (_, index) => {
		const id = index < 26 ? String.fromCharCode(65 + index) : "AA";
		return `### Part ${id} — Handle boundary ${index + 1}\n\nDescribe boundary ${index + 1}.`;
	}).join("\n\n");
	const result = parsePlanDocument(`# Many Parts\n\n## Context\n\nContext.\n\n## Approach\n\nApproach.\n\n${headings}\n`);
	assert.equal(result.ok, true, JSON.stringify(result.errors));
	assert.equal(result.document.parts.at(-1).id, "AA");
	assert.ok(errorCodes(PART_MINIMAL_PLAN.replace("Describe writes", "- **Targets:** \`src/cache.ts\`\n\nDescribe writes")).includes("disallowed_metadata"));
});

test("enforces size, heading hierarchy, and managed metadata guards", () => {
	assert.deepEqual(errorCodes(""), ["empty_plan"]);
	assert.deepEqual(errorCodes(`${PART_PLAN}${"x".repeat(MAX_PLAN_BYTES)}`), ["plan_too_large"]);
	assert.ok(errorCodes(PART_PLAN.replace("### Part A", "#### Part A")).includes("unsupported_heading"));
	assert.ok(errorCodes(PART_PLAN.replace("### Part A — Define cache consistency", "### Part A — Define cache consistency\n- **Ledger:** {\"status\":\"pending\"}")).includes("managed_metadata_forbidden") === false);
	assert.equal(parsePlanDocument(PART_PLAN.replace("### Part A — Define cache consistency", "### Part A — Define cache consistency\n- **Ledger:** {\"status\":\"pending\"}"), { allowManagedMetadata: false }).ok, false);
});
